# Generated by Django 5.2.6 on 2025-11-16 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0006_bookingdetail_addons_alter_addon_seat_class_and_more'),
        ('instructorapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityAddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=False, help_text='Whether this add-on is mandatory for the activity')),
                ('quantity_per_passenger', models.PositiveIntegerField(default=1, help_text='How many of this add-on each passenger should have')),
                ('notes', models.TextField(blank=True, help_text='Additional instructions for this add-on', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_addons', to='instructorapp.activity')),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_requirements', to='flightapp.addon')),
            ],
            options={
                'verbose_name_plural': 'Activity Add-ons',
                'unique_together': {('activity', 'addon')},
            },
        ),
    ]
