# Generated by Django 5.2.6 on 2025-10-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instructorapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(default='Flight Booking', max_length=50),
        ),
    ]
