# Generated by Django 5.2.6 on 2025-12-04 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0002_alter_user_options_alter_user_managers_and_more'),
        ('instructorapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sectionenrollment',
            unique_together={('student', 'section')},
        ),
    ]
