# Generated by Django 5.2.6 on 2025-10-09 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instructorapp', '0002_alter_activity_activity_type'),
        ('flightapp', '0002_user_last_login'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitysubmission',
            options={},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sectionenrollment',
            options={},
        ),
        migrations.RemoveField(
            model_name='activitysubmission',
            name='grading_details',
        ),
        migrations.RemoveField(
            model_name='activitysubmission',
            name='max_score',
        ),
        migrations.RemoveField(
            model_name='activitysubmission',
            name='started_at',
        ),
        migrations.RemoveField(
            model_name='activitysubmission',
            name='submission_code',
        ),
        migrations.AddField(
            model_name='activity',
            name='required_return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_submissions', to='flightapp.booking'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='required_travel_class',
            field=models.CharField(choices=[('economy', 'Economy'), ('premium_economy', 'Premium Economy'), ('business', 'Business'), ('first', 'First Class')], default='economy', max_length=20),
        ),
        migrations.AlterField(
            model_name='activitysubmission',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('graded', 'Graded'), ('late', 'Late Submission')], default='submitted', max_length=20),
        ),
        migrations.AlterField(
            model_name='activitysubmission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_submissions', to='flightapp.student'),
        ),
        migrations.AlterField(
            model_name='activitysubmission',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='academic_year',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='section',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='flightapp.user'),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='section',
            name='semester',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sectionenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_enrollments', to='flightapp.student'),
        ),
    ]
