# Generated by Django 5.2.6 on 2025-11-16 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructorapp', '0002_activityaddon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityaddon',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_addons', to='instructorapp.activity'),
        ),
    ]
