# Generated by Django 5.2.6 on 2025-11-16 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0006_bookingdetail_addons_alter_addon_seat_class_and_more'),
        ('instructorapp', '0003_alter_activityaddon_activity'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='activityaddon',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='activityaddon',
            name='passenger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passenger_addons', to='instructorapp.activitypassenger'),
        ),
        migrations.AlterUniqueTogether(
            name='activityaddon',
            unique_together={('activity', 'addon', 'passenger')},
        ),
    ]
