# Generated by Django 5.2.6 on 2025-10-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instructorapp', '0003_alter_activitysubmission_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='require_contact',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='require_date_of_birth',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='require_full_name',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='require_gender',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='require_nationality',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='require_passport',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='required_children',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activity',
            name='required_infants',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
