# Generated by Django 5.2.6 on 2025-11-16 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructorapp', '0004_alter_activityaddon_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='code_expires_at',
        ),
    ]
