# Generated by Django 5.2.6 on 2025-10-09 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructorapp', '0004_activity_require_contact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='require_date_of_birth',
            new_name='require_passenger_details',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='require_contact',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='require_full_name',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='require_gender',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='require_nationality',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='require_passport',
        ),
    ]
