# Generated by Django 5.2.6 on 2025-11-16 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0006_bookingdetail_addons_alter_addon_seat_class_and_more'),
        ('instructorapp', '0005_remove_activity_code_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='addon_grading_enabled',
            field=models.BooleanField(default=True, help_text='Enable grading for add-ons'),
        ),
        migrations.AddField(
            model_name='activity',
            name='required_addon_points',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum points required from add-ons', max_digits=6),
        ),
        migrations.AddField(
            model_name='activityaddon',
            name='points_value',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Points awarded for including this add-on', max_digits=6),
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='addon_feedback',
            field=models.TextField(blank=True, help_text='Feedback specific to add-on selection'),
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='addon_score',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Points earned from add-ons', max_digits=6),
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='max_addon_points',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Maximum possible points from add-ons', max_digits=6),
        ),
        migrations.CreateModel(
            name='StudentSelectedAddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_selected', models.PositiveIntegerField(default=1)),
                ('points_earned', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity_addon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_selections', to='instructorapp.activityaddon')),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_selections', to='flightapp.addon')),
                ('booking_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected_addons', to='flightapp.bookingdetail')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_addons', to='instructorapp.activitysubmission')),
            ],
            options={
                'unique_together': {('submission', 'activity_addon', 'addon')},
            },
        ),
    ]
