# Generated by Django 5.2.5 on 2025-10-10 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructorapp', '0006_activitypassenger'),
        ('flightapp', '0002_user_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitysubmission',
            name='require_passenger_details',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='required_children',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='required_destination_airport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_destinations', to='flightapp.airport'),
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='required_infants',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='required_max_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='required_origin_airport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_origins', to='flightapp.airport'),
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='required_passengers',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='required_travel_class',
            field=models.CharField(choices=[('economy', 'Economy'), ('premium_economy', 'Premium Economy'), ('business', 'Business'), ('first', 'First Class')], default='economy', max_length=20),
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='required_trip_type',
            field=models.CharField(choices=[('one_way', 'One Way'), ('round_trip', 'Round Trip')], default='one_way', max_length=20),
        ),
    ]
