# Generated by Django 5.2.5 on 2025-10-11 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructorapp', '0007_activitysubmission_require_passenger_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitypassenger',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='instructorapp.activity'),
        ),
    ]
