# Generated by Django 5.2.6 on 2025-11-18 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructorapp', '0007_remove_activity_required_max_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitypassenger',
            name='passport_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
