# Generated by Django 5.2.6 on 2025-10-21 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0002_user_last_login'),
        ('instructorapp', '0008_alter_activitypassenger_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('practice_type', models.CharField(choices=[('free_practice', 'Free Practice'), ('guided_practice', 'Guided Practice')], default='free_practice', max_length=20)),
                ('scenario_description', models.TextField(blank=True, null=True)),
                ('practice_requirements', models.JSONField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_booking', to='flightapp.booking')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_bookings', to='flightapp.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
