# Generated by Django 5.2.6 on 2025-11-18 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructorapp', '0008_activitypassenger_passport_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='require_passport',
            field=models.BooleanField(default=False, help_text='Require passport information for all passengers'),
        ),
    ]
