# Generated by Django 5.2.6 on 2025-11-18 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructorapp', '0009_activity_require_passport'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitypassenger',
            name='passenger_type',
            field=models.CharField(choices=[('adult', 'Adult'), ('child', 'Child'), ('infant', 'Infant')], default='adult', max_length=10),
        ),
    ]
