# Generated by Django 5.2.6 on 2025-11-19 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0009_alter_passengerinfo_nationality'),
        ('instructorapp', '0011_alter_section_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='flightapp.user'),
        ),
    ]
