# Generated by Django 5.2.6 on 2025-11-19 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0010_instructor_user'),
        ('instructorapp', '0014_alter_section_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='flightapp.instructor'),
        ),
    ]
