# Generated by Django 5.2.6 on 2025-12-02 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0013_taxtype_traveltaxrate_airport_city_airport_country_and_more'),
        ('instructorapp', '0015_alter_section_instructor'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sectionenrollment',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='sectionenrollment',
            constraint=models.UniqueConstraint(fields=('student',), name='unique_student_section_enrollment'),
        ),
    ]
