# Generated by Django 5.2.6 on 2025-12-02 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructorapp', '0016_alter_sectionenrollment_unique_together_and_more'),
    ]

    operations = [
    ]
