# Generated by Django 5.2.6 on 2025-12-02 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0013_taxtype_traveltaxrate_airport_city_airport_country_and_more'),
        ('instructorapp', '0017_auto_20251202_1208'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sectionenrollment',
            name='unique_student_section_enrollment',
        ),
        migrations.AlterUniqueTogether(
            name='sectionenrollment',
            unique_together={('student', 'section')},
        ),
    ]
