# Generated by Django 5.2.5 on 2025-09-05 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0002_schedule_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('Standby', 'Standby'), ('On Flight', 'On Flight'), ('Arrived', 'Arrived')], default='Standby', max_length=10),
        ),
    ]
