# Generated by Django 5.2.6 on 2025-11-07 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0002_addon_remove_instructor_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_classes', to='flightapp.airline')),
            ],
            options={
                'unique_together': {('airline', 'name')},
            },
        ),
        migrations.AddField(
            model_name='flight',
            name='flight_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flights', to='flightapp.flightclass'),
        ),
    ]
