# Generated by Django 5.2.5 on 2025-08-22 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0002_remove_student_password_remove_student_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='min_parked_duration',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flightapp.flight'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('parked', 'Parked'), ('departed', 'Departed'), ('landed', 'Landed')], default='parked', max_length=10),
        ),
    ]
