# Generated by Django 5.2.5 on 2025-10-16 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0002_addon_bookingaddon'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='airport_type',
            field=models.CharField(choices=[('domestic', 'Domestic'), ('international', 'International'), ('unknown', 'Unknown')], default='unknown', max_length=20, verbose_name='Airport Type'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='location',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.DeleteModel(
            name='BookingAddOn',
        ),
    ]
