# Generated by Django 5.2.5 on 2025-10-17 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0003_airport_airport_type_alter_airport_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Instructor',
        ),
    ]
