# Generated by Django 5.2.6 on 2025-11-07 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0003_flightclass_flight_flight_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOnType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='addon',
            name='airline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='flightapp.airline'),
        ),
        migrations.AddField(
            model_name='addon',
            name='flight_class',
            field=models.ForeignKey(blank=True, help_text='If included=True, this add-on is automatically included in this flight class.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addons', to='flightapp.flightclass'),
        ),
        migrations.AddField(
            model_name='addon',
            name='included',
            field=models.BooleanField(default=False, help_text='If true, this add-on is automatically included with the flight class.'),
        ),
        migrations.AlterField(
            model_name='flightclass',
            name='airline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flight_classes', to='flightapp.airline'),
        ),
        migrations.AlterField(
            model_name='flightclass',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='addon',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addons', to='flightapp.addontype'),
        ),
    ]
