# Generated by Django 5.2.5 on 2025-08-22 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0003_schedule_min_parked_duration_alter_schedule_flight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='min_parked_duration',
        ),
        migrations.AddField(
            model_name='schedule',
            name='parked_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('parked', 'Parked'), ('departed', 'Departed'), ('landed', 'Landed')], max_length=10),
        ),
    ]
