# Generated by Django 5.2.5 on 2025-08-24 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0004_remove_schedule_min_parked_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('parked', 'Parked'), ('departed', 'Departed'), ('landed', 'Landed')], default='parked', max_length=10),
        ),
    ]
