# Generated by Django 5.2.6 on 2025-11-07 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0004_addontype_addon_airline_addon_flight_class_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='flight_class',
        ),
        migrations.RemoveField(
            model_name='addon',
            name='flight_class',
        ),
        migrations.AddField(
            model_name='addon',
            name='seat_class',
            field=models.ForeignKey(blank=True, help_text='If included=True, this add-on is automatically included with this seat class.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addons', to='flightapp.seatclass'),
        ),
        migrations.AddField(
            model_name='seatclass',
            name='airline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seat_classes', to='flightapp.airline'),
        ),
        migrations.AddField(
            model_name='seatclass',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the seat class amenities', null=True),
        ),
        migrations.AlterField(
            model_name='addon',
            name='included',
            field=models.BooleanField(default=False, help_text='If true, this add-on is automatically included with the seat class.'),
        ),
        migrations.AlterUniqueTogether(
            name='seatclass',
            unique_together={('airline', 'name')},
        ),
        migrations.DeleteModel(
            name='FlightClass',
        ),
    ]
