# Generated by Django 5.2.5 on 2025-10-17 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0004_alter_user_role_delete_instructor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_initial', models.CharField(blank=True, max_length=5, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('instructor_id', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
