# Generated by Django 5.2.5 on 2025-09-08 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0004_instructorprofile_studentprofile_user_delete_myuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('instructor', 'Instructor')], max_length=20),
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
    ]
