# Generated by Django 5.2.5 on 2025-09-10 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0005_alter_user_role_delete_studentprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flightapp.schedule'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('Open', 'Open for Booking'), ('Closed', 'Closed'), ('On Flight', 'On Flight'), ('Arrived', 'Arrived')], default='Open', max_length=10),
        ),
    ]
