# Generated by Django 5.2.5 on 2025-08-24 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0005_alter_schedule_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='status',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='parked_minutes',
            field=models.IntegerField(default=0),
        ),
    ]
