# Generated by Django 5.2.5 on 2025-10-29 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0002_user_last_login'),
        ('flightapp', '0005_instructor'),
    ]

    operations = [
    ]
