# Generated by Django 5.2.6 on 2025-11-16 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0005_remove_flight_flight_class_remove_addon_flight_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdetail',
            name='addons',
            field=models.ManyToManyField(blank=True, related_name='booking_details', to='flightapp.addon'),
        ),
        migrations.AlterField(
            model_name='addon',
            name='seat_class',
            field=models.ForeignKey(blank=True, help_text='If included=True, this add-on is automatically included in this seat class.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addons', to='flightapp.seatclass'),
        ),
        migrations.AlterField(
            model_name='seatclass',
            name='airline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seat_classes', to='flightapp.airline'),
        ),
        migrations.AlterField(
            model_name='seatclass',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
