# Generated by Django 5.2.6 on 2025-11-18 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0006_bookingdetail_addons_alter_addon_seat_class_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passengerinfo',
            name='email',
        ),
        migrations.RemoveField(
            model_name='passengerinfo',
            name='phone',
        ),
    ]
