# Generated by Django 5.2.5 on 2025-09-10 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0006_alter_booking_schedule_alter_schedule_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='schedule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='flightapp.schedule'),
            preserve_default=False,
        ),
    ]
