# Generated by Django 5.2.5 on 2025-08-24 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0006_remove_schedule_status_alter_schedule_parked_minutes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='parked_minutes',
        ),
    ]
