# Generated by Django 5.2.6 on 2025-11-19 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0007_remove_passengerinfo_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengerinfo',
            name='nationality',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
