# Generated by Django 5.2.6 on 2025-11-19 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0008_passengerinfo_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengerinfo',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
