# Generated by Django 5.2.5 on 2025-09-10 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0008_alter_booking_created_at_alter_booking_schedule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='seat',
        ),
        migrations.AddField(
            model_name='booking',
            name='outbound_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outbound_bookings', to='flightapp.schedule'),
        ),
        migrations.AddField(
            model_name='booking',
            name='outbound_seat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_seat_bookings', to='flightapp.seat'),
        ),
        migrations.AddField(
            model_name='booking',
            name='return_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_bookings', to='flightapp.schedule'),
        ),
        migrations.AddField(
            model_name='booking',
            name='return_seat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_seat_bookings', to='flightapp.seat'),
        ),
    ]
