# Generated by Django 5.2.5 on 2025-08-24 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0008_alter_schedule_flight'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('Standby', 'Standby'), ('On Flight', 'On Flight'), ('Arrived', 'Arrived')], default='Standby', max_length=20),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flightapp.flight'),
        ),
    ]
