# Generated by Django 5.2.5 on 2025-08-24 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0009_schedule_status_alter_schedule_flight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='status',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='flightapp.flight'),
        ),
    ]
