# Generated by Django 5.2.5 on 2025-09-10 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0009_remove_booking_schedule_remove_booking_seat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='trip_type',
            field=models.CharField(choices=[('one_way', 'One Way'), ('round_trip', 'Round Trip')], default='one_way', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='outbound_seat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_seats', to='flightapp.seat'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='return_seat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_seats', to='flightapp.seat'),
        ),
    ]
