# Generated by Django 5.2.6 on 2025-11-19 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0009_alter_passengerinfo_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructor_profile', to='flightapp.user'),
        ),
    ]
