# Generated by Django 5.2.5 on 2025-09-11 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0010_booking_trip_type_alter_booking_outbound_seat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='outbound_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_bookings', to='flightapp.schedule'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='return_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_bookings', to='flightapp.schedule'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='trip_type',
            field=models.CharField(choices=[('one_way', 'One-way'), ('round_trip', 'Round-trip')], max_length=20),
        ),
    ]
