# Generated by Django 5.2.5 on 2025-08-27 04:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0010_remove_schedule_status_alter_schedule_flight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='student',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='bookingdetail',
            name='passenger_email',
        ),
        migrations.RemoveField(
            model_name='bookingdetail',
            name='passenger_first_name',
        ),
        migrations.RemoveField(
            model_name='bookingdetail',
            name='passenger_last_name',
        ),
        migrations.RemoveField(
            model_name='bookingdetail',
            name='passenger_phone',
        ),
        migrations.RemoveField(
            model_name='bookingdetail',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='bookingdetail',
            name='seat',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='price',
        ),
        migrations.AddField(
            model_name='bookingdetail',
            name='seat_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='bookingdetail',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flightapp.flight'),
        ),
        migrations.AlterField(
            model_name='bookingdetail',
            name='seat_class',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='PassengerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('passport_number', models.CharField(blank=True, max_length=50, null=True)),
                ('booking_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='flightapp.bookingdetail')),
            ],
        ),
        migrations.CreateModel(
            name='TrackLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flightapp.passengerinfo')),
            ],
        ),
    ]
