# Generated by Django 5.2.6 on 2025-11-19 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0010_instructor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('instructor', 'Instructor'), ('student', 'Student')], max_length=20),
        ),
    ]
