# Generated by Django 5.2.5 on 2025-09-11 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0011_alter_booking_outbound_schedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='outbound_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outbound_bookings', to='flightapp.schedule'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='outbound_seat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_bookings', to='flightapp.seat'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='return_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_bookings', to='flightapp.schedule'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='return_seat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_bookings', to='flightapp.seat'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='trip_type',
            field=models.CharField(choices=[('one_way', 'One Way'), ('round_trip', 'Round Trip'), ('multi_city', 'Multi City')], max_length=20),
        ),
    ]
