# Generated by Django 5.2.5 on 2025-08-27 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0011_remove_booking_payment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passengerinfo',
            name='booking_detail',
        ),
    ]
