# Generated by Django 5.2.5 on 2025-08-27 06:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0012_remove_passengerinfo_booking_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingdetail',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='booking',
        ),
        migrations.AddField(
            model_name='bookingdetail',
            name='booking_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
