# Generated by Django 5.2.6 on 2025-12-02 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0012_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('per_passenger', models.BooleanField(default=True)),
                ('adult_only', models.BooleanField(default=False)),
                ('applies_domestic', models.BooleanField(default=True)),
                ('applies_international', models.BooleanField(default=True)),
                ('base_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='TravelTaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_type', models.CharField(choices=[('Adult', 'Adult'), ('Child', 'Child'), ('Infant', 'Infant')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='airport',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='airport',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='addon',
            name='included',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='addon',
            name='seat_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addons', to='flightapp.seatclass'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='airport_type',
            field=models.CharField(choices=[('domestic', 'Domestic'), ('international', 'International'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='passengerinfo',
            name='linked_adult',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infants', to='flightapp.passengerinfo'),
        ),
        migrations.CreateModel(
            name='InsurancePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('coverage_description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_plans', to='flightapp.airline')),
            ],
        ),
        migrations.CreateModel(
            name='BookingDetailInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('booking_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance', to='flightapp.bookingdetail')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flightapp.insuranceplan')),
            ],
            options={
                'verbose_name_plural': 'Booking Detail Insurances',
            },
        ),
        migrations.CreateModel(
            name='BookingTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('booking_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxes', to='flightapp.bookingdetail')),
                ('tax_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flightapp.taxtype')),
            ],
            options={
                'verbose_name_plural': 'Booking Taxes',
            },
        ),
        migrations.CreateModel(
            name='AirportFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='flightapp.airport')),
                ('tax_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flightapp.taxtype')),
            ],
            options={
                'unique_together': {('airport', 'tax_type')},
            },
        ),
        migrations.CreateModel(
            name='AirlineTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_rates', to='flightapp.airline')),
                ('tax_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airline_rates', to='flightapp.taxtype')),
            ],
            options={
                'unique_together': {('airline', 'tax_type')},
            },
        ),
    ]
