# Generated by Django 5.2.5 on 2025-09-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0013_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='is_available',
            field=models.BooleanField(choices=[(True, 'Available'), (False, 'Unavailable')], default=True),
        ),
    ]
