# Generated by Django 5.2.6 on 2025-12-02 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0014_country_alter_airport_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
