# Generated by Django 5.2.5 on 2025-09-17 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0014_alter_seat_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengerinfo',
            name='passenger_type',
            field=models.CharField(choices=[('Adult', 'Adult'), ('Child', 'Child'), ('Infant', 'Infant')], default='Adult', max_length=10),
        ),
        migrations.AlterField(
            model_name='passengerinfo',
            name='gender',
            field=models.CharField(max_length=10),
        ),
    ]
