# Generated by Django 5.2.5 on 2025-09-17 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0015_passengerinfo_passenger_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='seat',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
