# Generated by Django 5.2.6 on 2025-12-03 03:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0015_remove_instructor_user_remove_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon_class', models.CharField(blank=True, help_text="CSS class for icon (e.g., 'fas fa-stethoscope')", max_length=50, null=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which benefits are displayed')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='insuranceplan',
            name='airline',
        ),
        migrations.AddField(
            model_name='addon',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addon',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='TravelInsurancePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coverage_duration_days', models.PositiveIntegerField(default=30, help_text='Number of days coverage is valid')),
                ('medical_coverage', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Medical Coverage Amount')),
                ('trip_cancellation_coverage', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Trip Cancellation Coverage')),
                ('baggage_coverage', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Baggage Coverage')),
                ('personal_accident_coverage', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Personal Accident Coverage')),
                ('flight_delay_coverage', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Flight Delay Coverage (per hour)')),
                ('plan_type', models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium'), ('comprehensive', 'Comprehensive')], default='standard', max_length=20)),
                ('best_for', models.CharField(blank=True, help_text='Who this plan is best for', max_length=200, null=True)),
                ('underwriter', models.CharField(blank=True, help_text='Insurance company underwriting this plan', max_length=200, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which plans are displayed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_plans', to='flightapp.airline')),
                ('benefits', models.ManyToManyField(blank=True, related_name='insurance_plans', to='flightapp.insurancebenefit')),
            ],
            options={
                'ordering': ['display_order', 'price'],
                'unique_together': {('airline', 'name')},
            },
        ),
        migrations.AddField(
            model_name='addon',
            name='insurance_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addon_links', to='flightapp.travelinsuranceplan'),
        ),
        migrations.AddField(
            model_name='bookingdetail',
            name='insurance_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_details', to='flightapp.travelinsuranceplan'),
        ),
        migrations.DeleteModel(
            name='BookingDetailInsurance',
        ),
        migrations.DeleteModel(
            name='InsurancePlan',
        ),
    ]
