# Generated by Django 5.2.5 on 2025-09-19 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0016_alter_booking_status_alter_seat_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instructor', to='flightapp.user')),
            ],
        ),
        migrations.DeleteModel(
            name='InstructorProfile',
        ),
    ]
