# Generated by Django 5.2.6 on 2025-12-03 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0016_insurancebenefit_remove_insuranceplan_airline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceCoverageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, help_text="e.g., 'PHP', 'hours', 'per hour'", max_length=50, null=True)),
                ('icon_class', models.CharField(blank=True, max_length=50, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='travelinsuranceplan',
            name='baggage_coverage',
        ),
        migrations.RemoveField(
            model_name='travelinsuranceplan',
            name='flight_delay_coverage',
        ),
        migrations.RemoveField(
            model_name='travelinsuranceplan',
            name='medical_coverage',
        ),
        migrations.RemoveField(
            model_name='travelinsuranceplan',
            name='personal_accident_coverage',
        ),
        migrations.RemoveField(
            model_name='travelinsuranceplan',
            name='trip_cancellation_coverage',
        ),
        migrations.CreateModel(
            name='PlanCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('description', models.TextField(blank=True, null=True)),
                ('coverage_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_coverage_links', to='flightapp.insurancecoveragetype')),
                ('insurance_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_coverages', to='flightapp.travelinsuranceplan')),
            ],
            options={
                'ordering': ['coverage_type__display_order'],
                'unique_together': {('insurance_plan', 'coverage_type')},
            },
        ),
    ]
