# Generated by Django 5.2.5 on 2025-09-19 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0017_route_base_price_instructor_delete_instructorprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='price',
        ),
    ]
