# Generated by Django 5.2.6 on 2025-12-03 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0017_insurancecoveragetype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxtype',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
