# Generated by Django 5.2.5 on 2025-09-19 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0018_remove_schedule_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='base_price',
        ),
        migrations.AddField(
            model_name='schedule',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
