# Generated by Django 5.2.5 on 2025-09-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0019_remove_route_base_price_schedule_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
