# Generated by Django 5.2.5 on 2025-09-22 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0020_route_base_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
