# Generated by Django 5.2.5 on 2025-09-27 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0021_booking_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='middle_initial',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
