# Generated by Django 5.2.5 on 2025-09-27 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0022_student_middle_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='middle_initial',
        ),
    ]
