# Generated by Django 5.2.5 on 2025-09-30 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0024_student_middle_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdetail',
            name='passenger',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='booking_details', to='flightapp.passengerinfo'),
            preserve_default=False,
        ),
    ]
