# Generated by Django 5.2.5 on 2025-09-30 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0025_bookingdetail_passenger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='outbound_seat',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='price',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='return_seat',
        ),
        migrations.AddField(
            model_name='bookingdetail',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bookingdetail',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flightapp.passengerinfo'),
        ),
    ]
