# Generated by Django 5.2.5 on 2025-09-30 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0026_remove_booking_outbound_seat_remove_booking_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingdetail',
            name='booking_date',
        ),
        migrations.RemoveField(
            model_name='bookingdetail',
            name='flight',
        ),
        migrations.RemoveField(
            model_name='bookingdetail',
            name='seat',
        ),
        migrations.RemoveField(
            model_name='bookingdetail',
            name='seat_class',
        ),
        migrations.AddField(
            model_name='bookingdetail',
            name='outbound_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outbound_booking_details', to='flightapp.schedule'),
        ),
        migrations.AddField(
            model_name='bookingdetail',
            name='outbound_seat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_booking_details', to='flightapp.seat'),
        ),
        migrations.AddField(
            model_name='bookingdetail',
            name='return_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_booking_details', to='flightapp.schedule'),
        ),
        migrations.AddField(
            model_name='bookingdetail',
            name='return_seat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_booking_details', to='flightapp.seat'),
        ),
        migrations.AlterField(
            model_name='bookingdetail',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flightapp.booking'),
        ),
    ]
