# Generated by Django 5.2.5 on 2025-09-30 17:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0029_remove_bookingdetail_booking_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingdetail',
            name='outbound_schedule',
        ),
        migrations.RemoveField(
            model_name='bookingdetail',
            name='outbound_seat',
        ),
        migrations.RemoveField(
            model_name='bookingdetail',
            name='return_schedule',
        ),
        migrations.RemoveField(
            model_name='bookingdetail',
            name='return_seat',
        ),
        migrations.AddField(
            model_name='bookingdetail',
            name='booking_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='bookingdetail',
            name='flight',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='flightapp.flight'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookingdetail',
            name='seat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flightapp.seat'),
        ),
        migrations.AddField(
            model_name='bookingdetail',
            name='seat_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flightapp.seatclass'),
        ),
        migrations.AlterField(
            model_name='bookingdetail',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='flightapp.booking'),
        ),
    ]
