# Generated by Django 5.2.5 on 2025-09-30 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0030_remove_bookingdetail_outbound_schedule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingdetail',
            name='flight',
        ),
        migrations.AddField(
            model_name='bookingdetail',
            name='schedule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='flightapp.schedule'),
            preserve_default=False,
        ),
    ]
