# Generated by Django 5.2.5 on 2025-09-30 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0031_remove_bookingdetail_flight_bookingdetail_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='outbound_schedule',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='return_schedule',
        ),
    ]
