# Generated by Django 5.2.5 on 2025-10-02 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0032_remove_booking_outbound_schedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdetail',
            name='guardian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependents', to='flightapp.passengerinfo'),
        ),
    ]
