# Generated by Django 5.2.5 on 2025-10-02 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0033_bookingdetail_guardian'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingdetail',
            name='guardian',
        ),
        migrations.AddField(
            model_name='bookingdetail',
            name='accompanying_adult',
            field=models.ForeignKey(blank=True, help_text='If passenger is an Infant, link to Adult passenger', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infants', to='flightapp.passengerinfo'),
        ),
        migrations.AddField(
            model_name='bookingdetail',
            name='passenger_type',
            field=models.CharField(choices=[('Adult', 'Adult'), ('Child', 'Child'), ('Infant', 'Infant')], default='Adult', max_length=20),
        ),
    ]
