# Generated by Django 5.2.5 on 2025-10-02 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0034_remove_bookingdetail_guardian_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingdetail',
            name='accompanying_adult',
        ),
        migrations.RemoveField(
            model_name='bookingdetail',
            name='passenger_type',
        ),
    ]
