# Generated by Django 5.2.5 on 2025-10-02 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0035_remove_bookingdetail_accompanying_adult_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengerinfo',
            name='linked_adult',
            field=models.ForeignKey(blank=True, help_text='For infants on lap, assign to the adult passenger', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infants', to='flightapp.passengerinfo'),
        ),
    ]
