# Generated by Django 5.2.6 on 2025-09-25 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_multicityleg'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='duration',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='multicityleg',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='master.booking'),
        ),
        migrations.AddField(
            model_name='multicityleg',
            name='duration',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='route',
            field=models.CharField(blank=True, choices=[('manila_cebu', 'Manila → Cebu'), ('cebu_manila', 'Cebu → Manila'), ('manila_davao', 'Manila → Davao'), ('davao_manila', 'Davao → Manila')], max_length=50, null=True),
        ),
    ]
