# Generated by Django 5.2.6 on 2025-09-26 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_booking_duration_multicityleg_booking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='route',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='multicityleg',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='master.booking'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='master.booking'),
        ),
    ]
